# Generated by Django 5.2 on 2025-04-20 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        default="Тип мероприятия не указан",
                        verbose_name="Тип мероприятия",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Название"
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата и время")),
                (
                    "price",
                    models.IntegerField(null=True, verbose_name="Стоимость посещения"),
                ),
                ("location", models.CharField(max_length=255, verbose_name="Место")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "registration_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на регистрацию"
                    ),
                ),
                ("image", models.ImageField(upload_to="events/", verbose_name="Фото")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, unique=True, verbose_name="Символьный код"
                    ),
                ),
                (
                    "event_type",
                    models.ForeignKey(
                        default="Тип мероприятия не указан",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="events.eventtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ["date"],
            },
        ),
    ]
