# Generated by Django 5.2 on 2025-04-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                null=True, upload_to="events/", verbose_name="Фото"
            ),
        ),
    ]
