# Generated by Django 5.2 on 2025-04-19 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="slag",
            new_name="slug",
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.ForeignKey(
                default="Тип мероприятия не указан",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="events.eventtype",
            ),
        ),
    ]
