# Generated by Django 5.2 on 2025-04-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_image"),
    ]

    operations = []
