FROM node:22 as builder
ARG MODE=development

ENV NODE_ENV=$MODE

WORKDIR /frontend
COPY package*.json ./

RUN npm install

COPY . /frontend/

EXPOSE 8080

CMD [ "npm", "install", "&&", "npm", "run", "host"]