# Сборка фронтенда
FROM node:20 AS builder

ARG BACKEND_URL
ENV VITE_BACKEND_URL=$BACKEND_URL
ENV NODE_ENV production
ENV HUSKY=0

WORKDIR /frontend

COPY package.json ./
COPY package-lock.json ./
RUN npm install

COPY . ./
RUN npm run build

# Продакшн сервер Nginx
FROM nginx:stable-alpine3.20-perl AS deploy

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /frontend/dist/ /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]