services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "3000:8000"
    environment:
      - DEBUG=1
    command: python manage.py runserver 0.0.0.0:8000

    depends_on:
      - db

  frontend:
      container_name: frontend
      build:
          context: ./frontend
          dockerfile: dockerfile.dev
          args:
              - MODE=${MODE}
      volumes:
          - ./frontend:/frontend
          - ./frontend/node_modules:/frontend/node_modules
      env_file: ./.env
      environment:
          - VITE_BACKEND_URL=${VITE_BACKEND_URL}
          - HUSKY=${FRONTEND_LINTING:?Variable FRONTEND_LINTING is required}
          - NODE_ENV=${MODE:?Variable Mode is required}
      ports:
          - 8000:5173
      depends_on:
          - backend
      command: sh ./run-server.sh
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

