services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend/static:/app/static
      - /var/www/monckeclub:/app/media
    expose:
      - "8000"
    environment:
      - DEBUG=0
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.prod
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  nginx:
        container_name: nginx-server
        build:
            context: ./frontend
            dockerfile: dockerfile.prod
            args:
                - BACKEND_URL=${VITE_BACKEND_URL}
        restart: unless-stopped
        env_file: ./.env
        environment:
            - VITE_BACKEND_URL=${VITE_BACKEND_URL}
            - HUSKY=0
            - NODE_ENV=production
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - /var/www/monckeclub:/app/media
            - ./backend/static:/app/static
        depends_on:
            - backend
        ports:
            - 80:80
        networks:
          - app-network

volumes:
  postgres_data:


networks:
  app-network: