# Generated by Django 5.2 on 2025-04-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TunTunTunSahurUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(default="", max_length=255)),
                ("is_banned", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
