# Generated by Django 5.2 on 2025-04-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_userbio_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbio",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=5),
        ),
    ]
