# Generated by Django 5.2 on 2025-04-20 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_create_mock_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbio",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.CreateModel(
            name="UserRatingActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("account_created", "Создание аккаунта"),
                            ("filled_description", "Заполнено описание"),
                            ("added_socials", "Добавлены соцсети"),
                            ("linked_subjects", "Добавлены предметы"),
                            ("verified", "Прошел верификацию"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "activity_type")},
            },
        ),
    ]
