# Generated by Django 5.2 on 2025-04-19 16:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Заявка без названия", verbose_name="Название заявки"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, unique=True, verbose_name="Символьный код"
                    ),
                ),
                (
                    "date_of_creation",
                    models.DateField(
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Дата создания заявки",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", verbose_name="Описание заявки"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Предложенная цена",
                    ),
                ),
                (
                    "is_finished",
                    models.BooleanField(
                        default=False, verbose_name="Статус выполнения заявки"
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                        ],
                        default=1,
                        verbose_name="Курс",
                    ),
                ),
                (
                    "executor_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_executor",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True,
                        to="marketplace.subject",
                        verbose_name="Теги типа задачи",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        to="marketplace.service",
                        verbose_name="Теги/тег предмета",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Юзер который создал заявку",
                    ),
                ),
            ],
        ),
    ]
