# Generated by Django 5.2 on 2025-04-19 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="date_of_creation",
            field=models.DateField(
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Дата создания заявки",
            ),
        ),
    ]
