# Generated by Django 5.2 on 2025-04-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/",
                verbose_name="Файл прикрепленный к заявке",
            ),
        ),
    ]
