# Generated by Django 5.2 on 2025-04-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_alter_application_date_of_creation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="service_id",
        ),
        migrations.RemoveField(
            model_name="application",
            name="subject_id",
        ),
        migrations.AddField(
            model_name="application",
            name="services",
            field=models.ManyToManyField(
                blank=True, to="marketplace.subject", verbose_name="Теги типа задачи"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, to="marketplace.service", verbose_name="Теги/тег предмета"
            ),
        ),
    ]
