# Generated by Django 5.2 on 2025-04-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_remove_application_service_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="slug",
            field=models.SlugField(
                blank=True, unique=True, verbose_name="Символьный код"
            ),
        ),
    ]
