# Generated by Django 5.2 on 2025-04-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_application_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="applications/",
                verbose_name="Файл прикрепленный к заявке",
            ),
        ),
    ]
