# Generated by Django 5.2 on 2025-04-19 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_mock_services_subjects"),
        ("marketplace", "0004_alter_application_file"),
    ]

    operations = []
