# Generated by Django 5.2 on 2025-04-19 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_alter_application_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="name",
            field=models.CharField(
                default="Заявка без названия",
                unique=True,
                verbose_name="Название заявки",
            ),
        ),
    ]
