# Generated by Django 5.2 on 2025-04-19 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_merge_20250419_2317"),
        ("marketplace", "0006_mock_applications"),
    ]

    operations = []
