# Generated by Django 5.2 on 2025-04-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_alter_application_name"),
        ("marketplace", "0007_merge_0005_merge_20250419_2317_0006_mock_applications"),
    ]

    operations = []
