# Generated by Django 5.2 on 2025-04-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_merge_20250420_0622"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="services",
            field=models.ManyToManyField(
                blank=True, to="marketplace.service", verbose_name="Теги типа задачи"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, to="marketplace.subject", verbose_name="Теги/тег предмета"
            ),
        ),
    ]
