# Generated by Django 5.2 on 2025-04-19 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="WorkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("data_created", models.DateTimeField(auto_now_add=True)),
                ("data_end", models.DateTimeField(blank=True, null=True)),
                ("price", models.PositiveIntegerField(blank=True, null=True)),
                ("job_experience", models.PositiveIntegerField(blank=True, null=True)),
                ("schedule", models.CharField(blank=True, max_length=255, null=True)),
                ("work_space", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "stack",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="vacancies",
                        to="vacancies.stack",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacancies",
                        to="vacancies.worktype",
                    ),
                ),
            ],
        ),
    ]
