# Generated by Django 5.2 on 2025-04-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="data_end",
            field=models.DateField(blank=True, null=True),
        ),
    ]
