# Generated by Django 5.2 on 2025-04-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0002_alter_vacancy_data_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
