# Generated by Django 5.2 on 2025-04-19 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0003_alter_vacancy_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="data_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="job_experience",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Опыт работы"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="schedule",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="График работы"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="stack",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="vacancies",
                to="vacancies.stack",
                verbose_name="Стек разработки",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="work_space",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Место работы"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="work_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vacancies",
                to="vacancies.worktype",
                verbose_name="Тип работы",
            ),
        ),
    ]
