name: deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Деплой
    runs-on: ubuntu-latest

    steps:
      - name: Клон репы
        uses: actions/checkout@v3

      - name: SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "/root/monke-club" ]; then
              cd /root
              git clone https://Topando:${{ secrets.GH_DEPLOY_TOKEN }}@github.com/MISIS-Monke-Club/monke-club.git
            fi

            cd /root/monke-club
            git pull origin develop
            docker-compose -f docker-compose.prod.yaml pull
            docker-compose -f docker-compose.prod.yaml up -d --build