name: CI for frontend and web-frontend
on: push

jobs:
  build:
    name: run ci for frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Dependencies
        run: npm install
        working-directory: ./frontend
      - name: Types
        run: npm run type-check
        working-directory: ./frontend
      - name: Linters
        run: npm run lint
        working-directory: ./frontend
      - name: Ability to Deploy
        run: npm run build
        working-directory: ./frontend